export { default as hat1 } from './01.png'
export { default as hat2 } from './02.png'
export { default as hat3 } from './03.png'
export { default as hat4 } from './04.png'
export { default as hat5 } from './05.png'
export { default as hat6 } from './06.png'
