export { default as cloth1 } from './01.png'
export { default as cloth2 } from './02.png'
export { default as cloth3 } from './03.png'
export { default as cloth4 } from './04.png'
export { default as cloth5 } from './05.png'
export { default as cloth6 } from './06.png'
export { default as cloth7 } from './07.png'
export { default as cloth8 } from './08.png'
